checksumBehavior: throw

defaultSemverRangePrefix: ''

enableGlobalCache: true

enableImmutableInstalls: true

enableScripts: false

enableStrictSsl: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'
npmMinimalAgeGate: 2880 # Must be 2 days old